### ISSUE TITLE
Consolidated Listing of Requested Changes

### ISSUE THREAD

**Issue by rsjaffe** [rsjaffe/MIDI2LR#31]
This is a consolidation of the various requests, organized by type of changes needed. I will add to this some discussion of the challenges and plans to address these. Keep checking this thread for more info.

**Anyone can contribute code to this project. At this point, most of the open requests require complex work, and help is greatly appreciated. In particular, support for non-MIDI controllers will probably not happen unless someone helps with writing and testing the code.**

Note that some changes may solve other problems. For example, instituting NRPN messages may solve some of the range issues, as that would allow variable-speed changes in parameters depending upon how quickly you rotate a dial. For broad-range parameters (e.g., temperature) this may end being preferred--we'll just have to see how it goes.

Tasks will be checked off as they are accomplished.

## New actions
- [x] @rojmagd #27 Choose modules: LrApplicationView.switchToModule( moduleName )
- [x] @edm81363 #4 Cycle Loupe View. LrApplicationView.showView( viewName ) "loupe", "grid", "compare", "survey", "people", "develop_loupe", "develop_before_after_horiz", "develop_before_after_vert", "develop_before"
- [x] @rojmagd #27 Create virtual copies catalog:createVirtualCopies( copyName )
- [x] @rojmagd #27 Copy and paste settings
- [x] @hzamir #61 These parameters (CropLeft,CropTop,CropRight,CropBottom,CropAngle) work in knobroom, so it is easy to dial in the edges of the image.
- [x] @krakozavr #78 Assign different parts of the "lens corrections" range (currently a slider/knob as implemented in the SDK) to buttons.
- [x] @krakozavr #73 ~~Select tone curve type. I will try implementing undocumented 'ToneCurveName' (e.g., "Medium Contrast").~~ Sorry, none of the undocumented tone curve commands worked.
- [x] @LUXIUS #26 @stevejmu #29 More functions select left, select right. Extend Selection: LrSelection.extendSelection( direction, amount )
- [x] @stevejmu #22 Assign presets to buttons: LrDevelopPresetFolder (Class) and LrDevelopPreset (Class)
- [x] @blende64 @micksh6 @pjparra @PhantomLordM #10 User selectable range for selected parameters (e.g., temperature, tint, exposure)
- [ ] @marcocucinato #9 Assign sequence of actions to button
- [ ] @marcocucinato @moutew @PhantomLordM #8 Assign calculated values to buttons (e.g., increase clarity by 2)
- [x] @rojmagd  #63 Customizable copy/paste to allow only certain parameters to be carried over in the paste operation.
- [x]  Paste options dialog that opens when pasting (as a new option, in addition to paste selected)
- [ ]  @krakozavr #89 Use *off* button signal for turning a value off. I will look into this--may interfere with current use of button to select an action with the *on* signal.
- [ ] @krakozavr #83 Keywording support.
- [x] @PhantomLordM @krakozavr #16 Assign tool controls (e.g., brush size) to MIDI controls. (this will require some hacking, as LR doesn't support this in their SDK). Note--done for adjustment sliders for localized tools, but not for brushes.
- [x] Assign local adjustment values to MIDI controls.
- [x] @losinternet #177 Local adjustments are missing the following: local whites, local blacks, local dehaze. These adjustments are missing from the LR SDK documentation, so we'll have to do some lucky guessing to get these running.

## UI changes
- [x] @LUXIUS #26 Start minimized (and give option to user to have start in regular mode)
- [x] 	#81 Show error if button mapping file cannot be saved (e.g., trying to save to program directory). Problem is line 114 of CommandMap.cpp: `root.writeToFile(file, "");` doesn't check return value of the function. If false, file write failed.
- [x] 	@krakozavr #108 Mark function already assigned in the main app's window. ~~Also, can it show how many assignments have been made for function?~~ Haven't figured out how to number it, but as of 0.8.2 shows red if already assigned.
- [x] @LUXIUS #26 Specific profiles for tools (Handy to be able to control crop tools when in crop mode)
- [x] @krakozavr #83 Show a screen-messages about currently using tools and adjustment's value, like it did in PADDY.

### Cross-platform solution will be needed: help wanted!
- [x] @clearminds @micksh6 @amycastell @stevejmu @fldutch #12 Map button to keyboard shortcuts
- [x] @stevejmu #217 @phaul2001 #203 @bozwellox #222 @AlePhoto  #200 User-selectable shortcuts.
- [x] @edm81363 @StefanKellerAC @alexlinno #5 ~~Send modifier keys when making adjustments~~ Due to a bug in Lightroom, this doesn't work. Lightroom ignores modifier keys when using the SDK to move sliders. I did implement this but then deleted it after testing confirmed this problem.
- [ ] @lukasradek #117 Add the ability to move zoomed image, if possible. In TouchOSC would be a great control for it XY Pad.
- [x] @MHPhotography #154 Function to Rotate Pictures left or right
- [x] @rojmagd #27 edit on photoshop, export, delete

### Will include some much-needed rearrangement of code and creation of encapsulating classes for controller model and LR model
- [ ] @rsjaffe @krakozavr #1 NRPN messages. Great news December 17, 2015: the Juce library, which is used by MIDI2LR to process MIDI messages, *finally* supports NRPN messages. That should accelerate progress here.
- [ ] @Henk72 #2 Behringer synch noise of motor
- [x] @rsjaffe #3 Send settings to MIDI controller
- [x] @LUXIUS #26 Toggle/select specific profiles (i.e. layers)
- [ ] @LUXIUS #26 Toggle button light when entering mode (Such as crop tool)
- [x] @LUXIUS @hzamir #26 Multiple buttons with same function. This is in the "enhance MIDI handling" section because this feature was *removed* in a previous version due to problems with knobs. We'll have to restrict this capability to buttons to avoid odd behaviors, which means we have to know which control is a knob and which a button.

## Other C++ application enhancements
- [ ] @krakozavr #80 Dialog to request to save mapping (if changed) when shutting down app.
- [ ] Support other types of controllers (e.g., Logitech G13). **For this, someone else will need to write the code**. You should have one of those controllers and knowledge of c++, along with knowledge of an SDK that can bridge between the controller and the MIDI2LR Juce SDK. If you need instructions on how to contribute code, see the github help pages. 
- [ ] @JaimeTak @hzamir #6 Be able to rearrange control order or sort like LR Command column
- [x] @laklare #190 Disable dialog box announcing new update or dismiss it once and not see it again.
- [ ] #143 @Jewest @StevenKersting Detect whether MIDI device connected or not. Stop plugin activity when not connected.

## Plugin changes
- [x] @renambot #14 Auto load on Mac.
- [ ] #148 @lukasradek @StevenKersting The ability for the program to send back on/off or user set signals (value/channel) would allow the indicator LEDs to change to indicate their current status/what they are controlling.
